services:
  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: "egorelusov"
      POSTGRES_USER: "egorelusov"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"

  vk:
    container_name: vk
    build: ./
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: postgres:5432
    depends_on:
      - postgres