spring:
  datasource:
    url: "jdbc:postgresql://postgres:5432/egorelusov"
    username: egorelusov
    password: 123

    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect


    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  jwtSecret: secret
  jwtExpirationInMs: 100
